### ISSUE TITLE
Figuring out MVP

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1]
Things to implement:
- [x] extrude puts cursor at extrude number #2 
- [x] [get Math/binaryexpressions working properly](https://github.com/KittyCAD/untitled-lang/issues/5)
- [x] [Comments and Whitespace should survive recasting](https://github.com/KittyCAD/untitled-lang/issues/9)
- [x] Uniform interface for functions #4 
- [x] #17
- [x] #19 
- [x] #25
- [x] #27
- [x] #31
- [x] #34
- [x] #29
  - [x] #33 
  - [x] #35
  - [x] #41
  - [x] #51
  - [x] #53
  - [x] #55
  - [x] #57
  - [x] Irev-Dev/sketch-helpers#1 Publish old sketch helper lib
  - [x] #59
  - [x] #64 (having something in the scene to "select" is important for adding constraints)
  - [x] #68
  - [x] #70
  - [x] #72
  - [x] #86
  - [x] #79
  - [x] #92
  - [x] #94
  - [x] #96
  - [x] #98
  - [x] #101
  - [x] #103
  - [x] #105 
  - [x] #107 
  - [x] #109
  - [x] #112
- [x] KittyCAD/infra#223
- [x] #40
- [x] #45
- [x] #61
- [x] #66
- [x] #74 
- [x] #76
- [x] #85
- [x] #88
- [x] #90
- [x] Move fake engine onto simple node app, in order to force the executor to run with async calls.
- [ ] xstate for UI modes/state (already have a mess of booleans for the current buttons)
- [ ] investigate branching logic (if statements) and how that will best work in a imutable environment and possibly with codegen
- [ ] investigate ast modifications within functions
- [ ] think more about metadata (vague I know I'll try and sure this up)
- [ ] plugin architecture for ui

Original description below
---

## What language is the intpreter written in?

Continue with TS for quicker iteration now (what Kurt knows best), or rust as better long term preformant option?
My gut feel is optimizing for speed of development to get it in front of people sooner means keeping it in TS for now. If it takes off, is getting lots of use and we want to refactor for performance, that's a good problem to have. We'll have lots of tests for the intepreter so doing a 1:1 port that we're confident in is do-able.

[edit]: rust migration is somewhat enable see: #27

## What are we looking to achieve this Q?

Hannah wrote "ast interaction thing", I think it's pretty reasonable to focus getting execution to tie in making api calls to our engine. Should also illuminate the problem to "GPU sessions", though probably need to still do some UI work, as in the lang needs to stay connected to the UI.
Would be good to have something a little more concrete to aim towards.

## UI tech?

The demo was built with as a react app, I think in 2023 we'd want this thing to run in a browser, but maybe the main path we guide people towards is a desktop app (https://tauri.app/?) since that's what mechies are used to. Though maybe it would be best start with a web app since we're only letting a small group of beta testers in, and that will be easy to update.

What's is the 3d viewer going to be? stick with a three.js scene? That means we need mesh artifacts, so probably not a long term option, though I'm not sure what the long term option would be? like a live render stream from the cloud?

## What we are NOT doing for the mvp
- modules that both
    - multiple file stuff (importing from code from seperate files)
    - or full blown dependencies and a crates.io style hub for them
- IDE niceties, syntax highlighting, auto complete etc (if its low effort sure, rest is the tech we're trying to prove and should get priority)

## What language features will we add

Generally it will lean towards the functional paradigm as removing state and mutability is going to make codegen easier. Here's a non-complete list of things I think should be in the language
- variable declartions with the common stuff: numbers, string, arrays, hashmaps
- function calls (at the very least with functions we provide)
- Very much want to enable branching logic (if statements) and function declaration, but want to confirum how they work with code-gen/ast-modification
- If the above is all good I've want to looping functionality, but probably in the form of `map` and other similar functions instead of `for(...)` syntax
```
['a','b','c']
    |> map(item => log(item), %)
```
- I would love to have types with inference in the language as well, but it's probably not a huge priority
