### ISSUE TITLE
KittyCAD app/lang task list

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#149]
We need to lock down the scope, we have a rough idea of modelling abilities, but there are so much more things to decide on in untitled app.

🧰 Dev tools
🧙 Code-gen (ast modification)
🤖 new engine capabilities
💅 App UI and layout

Not sure how important it is to parse out the buckets, but I'll use the emoji to indicate the bucket.

```[tasklist]
### ordered list
- [ ] https://github.com/KittyCAD/untitled-lang/issues/162
- [ ] https://github.com/KittyCAD/untitled-lang/issues/166
- [ ] https://github.com/KittyCAD/untitled-lang/issues/158
- [x] 🤖 🧙     Can extrude
- [ ] https://github.com/KittyCAD/untitled-lang/issues/160
- [ ] https://github.com/KittyCAD/modeling-app/issues/227
- [ ] https://github.com/KittyCAD/modeling-app/issues/228
- [ ] https://github.com/KittyCAD/modeling-app/issues/231
- [ ] https://github.com/KittyCAD/untitled-lang/issues/168
- [ ] https://github.com/KittyCAD/untitled-lang/issues/173
- [ ] https://github.com/KittyCAD/untitled-lang/issues/174
- [ ] https://github.com/KittyCAD/untitled-lang/issues/159
- [ ] https://github.com/KittyCAD/untitled-lang/issues/161
- [ ] https://github.com/KittyCAD/untitled-lang/issues/157
- [x] 🧰 A way to save the output of a script to formats we support from the command line and therefore in a GH action
- [x] 🤖 💅      Create a new sketch on one of the default planes
- [x] 🤖 💅      Scene can be put into a sketch mode, view is perpendicular to the sketch plane and with ortho camera
- [ ] https://github.com/KittyCAD/untitled-lang/issues/164
- [ ] https://github.com/KittyCAD/modeling-app/issues/574
- [ ] 🤖 💅      Embedded UI in the scene, Changing the length of an extrusion has annotations in the scene that show the direction of the extrusion, with some UI as well attached for changing the value
- [x] 🤖 🧙 💅 Draging the end of a segment moves the segment live and updates the code on mouse up
- [ ] https://github.com/KittyCAD/modeling-app/issues/575
- [ ] https://github.com/KittyCAD/modeling-app/issues/576
- [ ] 💅 Can use a keyboard shortcuts to sketch, line, and extrude
- [x] 💅 Cross platform packages signed with inbuilt updater
- [ ] https://github.com/KittyCAD/modeling-app/issues/295
- [ ] #296
```
```[tasklist]
### Out of beta-release scope
- [x] 🧙 🧰      AST helper panel (debuging for those developing plugins)
- [ ] 🤖           Can extrude-cut
- [ ] 🧙 🧰      Step through debugger
- [ ] 🤖           Loft
- [ ] 🧙           Dependency support (file paths and urls)
- [ ] 🤖 🧙 💅 Able to create 3d paths (not stuck to a plane)
- [ ] 🧙 🧰      Highlight multiple lines and transform into function
- [ ] 🤖 🧙 💅 Extrude along path
- [ ] 🧙 💅 🧰 drag variables into function name definition and it add's that variable as an input param
- [ ] 🧙 💅 🧰 Click variable name and drag it into literal value to substitue variable in
- [ ] 🤖           Revolve extrude
- [ ] https://github.com/KittyCAD/modeling-app/issues/793
- [ ] https://github.com/KittyCAD/untitled-lang/issues/163
- [ ] 🧙 💅      [Timeline debugger](https://github.com/KittyCAD/untitled-lang/assets/29681384/5b28d62b-1ad3-491a-b1da-25d43088975b)
- [ ] 🤖 project sketch onto non-planer surface
```

**Comment by jessfraz** [comment]
all these are covered in other issues
