### ISSUE TITLE
Fillet UI

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2606]
https://github.com/KittyCAD/modeling-app/assets/29681384/fcabab71-9b13-4576-8cc6-c5b4c7403981

related to https://github.com/KittyCAD/modeling-app/issues/729 roadmap
**Superseded by** #6617 – remaining fillet & chamfer work will be tracked there.

### chamfers
- [x] #4527
- [x] #4642
- [x] #4693

### todo
- [x] #2607
- [x] #2718
- [x] #3051
- [x] #3036
- [x] #3682
- [x] #3722
- [x] Refactor button states
- [x] #3675 (clean PR with only the artifact) 
- [x] #3833
- [x] #4039
- [x] #4082
- [x] #4112
- [x] #4381 
- [x] #4550
- [x] #4748
- [x] #4749
- [x] #4760
- [x] #4821
- [x] #5008
- [x] #5053
- [x] Enable Fillet in Nightly
- [x] #5239
- [x] #5358
- [x] make sure fillet works also with the cases when extrude is in the sketch pipe
- [x] #6618 

### multiple selections
- [x] #3831
- [x] #3680
- [x] #3834
- [x] #3943

### closed
- #3331

**Comment by max-mrgrsk** [comment]
I wonder what is a best visual solution in the viewport for conflict between fillets. First idea is to mark the edge with failed fillet with a red colour or an exclamation mark. 

<img width="1163" alt="Screenshot 2024-07-16 at 22 17 55" src="https://github.com/user-attachments/assets/0c8d1c7a-8a22-4249-b4ad-2cbf14c8f283">

**Comment by pierremtb** [comment]
@max-mrgrsk I removed the parent link to https://github.com/KittyCAD/engine/issues/1591, as it doesn't need to fully close before this huge feature issue for v1 can close. Which I can let you do now I think! ❤
