### ISSUE TITLE
Refactor artifact map

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3062]
The artifactMap code has survived so far from
- Synchronous fake engine
- Asynchronous 1:1 map between engine call and artifact
- A bad tangent where we tried to update the artifactMap without execution
- 1:many engine call to artifact (think solid3d_get_extrusion_face_info)
- batching

Tasks

```[tasklist]
### Main Tasks
- [ ] https://github.com/KittyCAD/modeling-app/pull/3084
- [ ] https://github.com/KittyCAD/modeling-app/issues/3104
- [x] ArtifactMap should have a white list (done in #3104)
- [ ] #3130
- [ ] https://github.com/KittyCAD/modeling-app/pull/3140
```

```[tasklist]
### Misc tasks (probably get pick up along the way, just don't want to forget)
- [x] rename command2
- [ ] type promiseFactory
```

**Comment by jessfraz** [comment]
can we close this?
