### ISSUE TITLE
Complete UI layout tweaks

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3087]
[These Figma mockups](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=3303-55650&t=tfYOpMNglv2SXj93-11) represent the next iteration of UI that we want to target in the near-term. Some of them have been completed already, but I want to make an issue to track the sub-tasks involved in completing this work:

```[tasklist]
### Tasks
- [x] Remove sidebar menus in favor of popovers (completed with #3046)
- [ ] Unify split sidebar ribbon, allow action buttons below the dividing line
- [ ] Show all tools in toolbar, add rich tooltips
- [ ] Add bottom status bar with state information
```

**Comment by franknoirot** [comment]
The last bit of this work would be implementing a status bar like the one I mocked up [here](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=4149-39751&t=juaC6TZxxHtrCBSl-11) a long time ago, based on VS Code's.

![bottom status bar mockup in Figma](https://github.com/user-attachments/assets/cd593f54-f87d-4077-a424-1c433e04d01d)
