### ISSUE TITLE
Tracking list of manual smoke tests before each release

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3588]
```[tasklist]
### Tasks
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
```

**Comment by lf94** [comment]
Can we put a process in place?

**Comment by lf94** [comment]
I was thinking maybe a spreadsheet with screenshot links that prove we have done the tests manually.

**Comment by jessfraz** [comment]
this is it haha, smoke test these for each os :)

**Comment by jessfraz** [comment]
oh that seems like a lot of work, I trust you all to actually do the thing, versus wasting time dealing w excel

**Comment by lf94** [comment]
We can save time by partitioning the tests amongst ourselves using a doc tho

**Comment by jessfraz** [comment]
fair fair set up whatever process you want :)

**Comment by franknoirot** [comment]
Maybe we auto-make a tasklist on "Cut release vXX.YY.ZZ" PRs

**Comment by nadr0** [comment]
The linux checklist I used on last release.

```
- [ ] Electron tests: external links open an external browser #3373 https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
  - [ ] !
  - [ ] Bug bottom folder page
  - [ ] Bug bottom model render page
  - [ ] (Does not work on linux) mod + shift + .
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
  - [ ] Opens directory
  - [ ] Creates main file if empty
- [ ] (Did not do) If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
  - [ ] /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/chassis-with-rails.kcl, took 47.60 seconds
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455  https://github.com/KittyCAD/modeling-app/issues/3455
  - [ ] Opening file
  - [ ] Editing file
  - [ ] ./out/Zoo\ Modeling\ App-linux-x64/zoo-modeling-app /home/kevin-nadro/smoke-test-file-permissions-linux/main.kcl
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469 https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] Electron: logging in and authing works #3465 https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] (Does not work on Linux) double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)

**Notes**
- Opening a path to a directory that doesn't exist, hangs, should we create the directory?
- Cannot figure out mod + shift + . on linux for core dump
- Double clicking files on linux does not work.
- Location to use the ZMA from the CLI ./out/Zoo\ Modeling\ App-linux-x64/zoo-modeling-app
- ```

**Comment by Irev-Dev** [comment]
for 
> running app.{app,exe} path/to/file opens the kcl file (all oses)
> running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)

on Macos

```bash
/Applications/Zoo\ Modeling\ App.app/Contents/MacOS/Zoo\ Modeling\ App /path/to/file
# Likely something like this
/Applications/Zoo\ Modeling\ App.app/Contents/MacOS/Zoo\ Modeling\ App /Users/<yourUser>/Documents/zoo-modeling-app-projects/projectName/fileName.kcl
```

**Comment by lf94** [comment]
I'm moving @jessfraz 's original post here just in case - it's been replaced with a more appropriate manual test tasklist.

---

```[tasklist]
### Manual Tasks
- [ ] Mash keyboard in code editor
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038
- [ ] Move around and sketch rapidly: is interaction still snappy?
```

also relevant [#3459](https://github.com/KittyCAD/modeling-app/issues/3459)

**Comment by pierremtb** [comment]
Proposed reduced smoke test list once a main ('nightly') build feels good

## Manual test tasklist: [add plaform here]

* [ ] The application opens
* [ ] Text-to-CAD works and the result can be viewed in an engine stream
* [ ] The auto-updater works
