### ISSUE TITLE
Cut release v0.30.0

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#4734]
Follow process at https://github.com/KittyCAD/modeling-app/blob/548c664db0e30876c9a9fcd6aeec30f9c1d89e6a/README.md?plain=1#L129

**Comment by pierremtb** [comment]
Planned for today or tomorrow

**Comment by pierremtb** [comment]
Building v0.30.0 release candidates from 00e9725 at https://github.com/KittyCAD/modeling-app/actions/runs/12279826579

**Comment by pierremtb** [comment]
## macOS

* [ ] The application opens
* [ ] User can sign in
* [ ] The onboarding can be replayed and looks solid
* [ ] A project can be created
* [ ] A sketch can be draw (line, arc, rect, circle).
* [ ] Lines and shapes can be modified.
* [ ] Select face and extruding works.
* [ ] Reloading the application gets you back in the same state
* [ ] Can create additional files and directories.
* [ ] Models can be exported to a file.
* [ ] I repeated some code done with point-and-click by typing in the code editor and everything was responsive and ok.
* [ ] Double clicking a KCL file opens ZMA, and with the CLI too on project directory or file
* [ ] Offset plane can be created and shows up
* [ ] The auto-updater works. 

Notes:
- Loft button still has a link to the github issue, should be removed (not a blocker to release)

**Comment by nadr0** [comment]
Grab the `out-ubuntu-22.04` AppImage from the `build-publish-apps` job in the CI CD pipeline of the PR that has the cut release. [Example](https://github.com/KittyCAD/modeling-app/actions/runs/11111096304) scroll to the bottom and see the artifacts sections to download the file.

> Gotcha: I had to `chmod +x` the file and install Fuse to get the AppImage running

> Use: updater-test-ubuntu-22.04 from the artifacts page for the update tests. 

- [ ] Electron tests: external links open an external browser #3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
  - [ ] !
  - [ ] Bug bottom folder page
  - [ ] Bug bottom model render page
  - [ ] :heavy_exclamation_mark: (Does not work on linux) mod + shift + .
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/cube.kcl
```
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
  - [ ] Opens directory
  - [ ] Creates main file if empty

```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default
```

```
rm /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty/main.kcl

/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty
```
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
    - [ ] xx.xx
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/chassis-with-rails.kcl
```
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455  
  - [ ] Opening file
  - [ ] Editing file
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/smoke-test-file-permissions-linux/main.kcl
```
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469 issues/3469
- [ ] Electron: logging in and authing works #3465 
- [ ] :heavy_exclamation_mark: (Does not work on Linux) double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Move around and sketch rapidly: is interaction still snappy?

**Notes**
- Opening a path to a directory that doesn't exist, hangs, should we create the directory?
```
Loading project at startup: /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2
Error: ENOENT: no such file or directory, stat '/home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2'
[42821:0930/142409.906556:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Checking for update
Update for version 0.25.5 is not available (latest version: 0.25.4, downgrade is disallowed).
```
- Cannot figure out mod + shift + . on linux for core dump
- Double clicking files on linux does not work.

**Comment by pierremtb** [comment]
[v30 is out](https://github.com/KittyCAD/modeling-app/releases/tag/v0.30.0)
