### ISSUE TITLE
Xstate migration clean up

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#817]
Clean up items from https://github.com/KittyCAD/modeling-app/pull/713
Related to #228

- [x] clean up toolbar.tsx, lots of commented out code in there (completed by. #865)
- [x] finish constraints, parallel and a few others are missing have a look in `src/components/Toolbar/` to see what is missing, and when finished clean those up (completed by. #865)
- [x] revert the reversion and resolve conflicts of https://github.com/KittyCAD/modeling-app/pull/813 related to the above (completed by. #865)
- [x] move `isCursorInSketchCommandRange` out of `useAppMode` and delete that file
- [x] #827
- [x] https://github.com/KittyCAD/modeling-app/issues/834
- [x] fix extrude bug (selecting extrude than a sketch is broken suddenly)
- [x] audit state diagram (probably @franknoirot and @Irev-Dev on a huddle)
- [ ] #818
- [ ] Still lots of logic in Stream.tsx,`handleMouseUp` in particular, consider if more of that should be moved into xstate actions
- [ ] decide what to do with the rest of useStore. There is definitely clean up to do, but do we want to move everything to xstate context or maybe just have some context/useReducer or something for the little bit of state we might want to keep in there
- [x] #819
- [ ] It's possible the constraints could be condensed into a single `add constraint` event that has different data instead of unique event per constraint, decide if this should change or not.

**Comment by Irev-Dev** [comment]
`clean up toolbar.tsx ...` and `revert the reversion ...` completed by. #865

**Comment by franknoirot** [comment]
> It's possible the constraints could be condensed into a single add constraint event that has different data instead of unique event per constraint, decide if this should change or not.

One thing I will say about this is that I'm not sure how the command bar will know about different commands if there aren't distinct events on the state machine for them. We'd end up having to add logic to support splitting out what kind of constraint you want to apply. I don't think it would be beneficial other than visually tidying up the XState diagram

**Comment by Irev-Dev** [comment]
I think the main thing is it's a better plugin architecture, but it probably makes sense to get the app working how we want it and then figure out how things might need to be refactored for that, and it's really not a priority anyway.

**Comment by Irev-Dev** [comment]
Of the 4 open tasks, the last one is the only relevant one still, and it's not something we'll forget about.
