### ISSUE TITLE
long list of manual things to test

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#833]
@Irev-Dev @paultag @pierremtb @franknoirot please add to this

eventually we will want to automate these things but we should test these before releases

related to
- #684 
- https://github.com/KittyCAD/modeling-app/issues/536

-----

-- edit Kurt: Turning these into checkboxes to keep track of e2e tests I'm writing

- [x] can authenticate
- [x] test for https://github.com/KittyCAD/modeling-app/issues/1558
- [ ] you should be able to create a sketch and generate code from the onboarding example code
- [ ] code stays between refreshes of app
- [ ] in tauri app, code re-executed when selecting a new file, should zoom to fit
- [ ] in tauri should zoom to fit when opening new project
- [ ] when you update your units in project settings / user settings it re-renders
- [ ] when you type the keybindings outside the editor it re-formats the code
- [x] when you type the keybindings inside the editor it re-formats the code
- [ ] when you are already in an indented line in pipe going to a new line also indents
- [ ] going from having a rendered model, then delete all code, then you should be able to start sketch again by clicking button and selecting a plane
- [ ] sketching next to the part from the onboarding should work just like everything else
- [x] errors from execution show up in the gutter and error pane
- [x] if you write invalid kcl you get inlined errors
- [x] code executes on initial page load in web app
- [x] typing in the editor re-executes the model and changes it based on your code
- [x] on startsketch click, you see the three planes
- [x] pan, zoom, moving model works
- [x] you can create new sketches w click and point
- [x] you can create a sketch on any plane (`xy`, `yz`, `xz`, `-xy`, `-yz`, `-xz`)
- [x] autocomplete works
- [ ] when engine stops and restarts, code re-executes and you get the gizmo and planes
- [ ] you can change your keyboard shortcuts to other settings and they work
- [x] #1110
- [ ] you can edit sketches, as long as they are not closed
- [ ] you should not be able to edit sketches that are closed, the button should not appear
- [ ] you can move lines in edit sketch and it updates the code (more than once)
- [x] #1112
- [ ] in tauri can create new projects
- [x] can apply constraints in edit sketch mode
- [x] #1139 you can export your model in each file type and the exported file is valid (done besides https://github.com/KittyCAD/modeling-app/issues/1140)
- [x] #1111
- [x] if you add constraints the code is stored for refresh https://github.com/KittyCAD/modeling-app/issues/861
- [x] if you restart the onboarding it re-executes with the new code for the onboarding https://github.com/KittyCAD/modeling-app/issues/862
- [x] #1136 Selections should work 
  - start a new sketch
  - create a few line segments
  - de-select the line tool
  - hover over a few segments to check it highlights the correct range in the code
  - exit and re-enter the sketch and check hovering agin

**Comment by mlfarrell** [comment]
Once/If we get a QA agency in place, we can lean on their experience to put together a full regression testing plan, smoke testing plan (subset of these testing most crucial), etc etc.  All based on this list.

**Comment by franknoirot** [comment]
- You can navigate to any shown link and get a page, no 404ing links
- You can open an empty file without engine/stream/app issue
- You can open a file with syntax errors without engine/stream/app issue 
- You can replay the onboarding from the home settings
- You can replay the onboarding from a project's settings
- Replaying the onboarding doesn't delete your file

**Comment by pierremtb** [comment]
List to be covered by e2e tauri tests:
- https://github.com/KittyCAD/modeling-app/issues/684 (app launches and the sign in button can be clicked)
- Authentication on Linux
- Create a file and expect engine to fail on Linux
- Get the tests to work on Windows
- Create a file on Windows and test sample code

**Comment by jessfraz** [comment]
closing because between qawolf and our most recent electron tests issues i think we are covered here.
